//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ARTICLES
    {
        public T_ARTICLES()
        {
            this.TP_PAYS = new HashSet<TP_PAYS>();
        }
    
        public decimal DOC_I_ID { get; set; }
        public Nullable<decimal> RUB_I_ID { get; set; }
        public string PUB_S_ID { get; set; }
        public decimal DOC_I_ID_EDITEUR { get; set; }
        public string ART_S_SURTITRE { get; set; }
        public string ART_S_TITRE { get; set; }
        public string ART_S_SOUS_TITRE { get; set; }
        public string ART_S_SUJET { get; set; }
        public string ART_S_CHAPEAU { get; set; }
        public string ART_S_TEXTE { get; set; }
        public Nullable<System.DateTime> ART_DT_PUBLICATION { get; set; }
        public Nullable<System.DateTime> ART_DT_PUBLICATION_WEB { get; set; }
        public Nullable<int> ART_I_NUM_PUBLICATION { get; set; }
        public Nullable<bool> ART_B_VALIDE { get; set; }
        public string ART_S_RUBRIQUES { get; set; }
        public string ART_S_PAYS { get; set; }
        public string ART_S_PUBLICATION { get; set; }
        public string SER_S_ID { get; set; }
        public string ART_S_LANGUE { get; set; }
        public string ART_S_REGION { get; set; }
        public string ART_S_SOUSREGION { get; set; }
        public string ART_S_SOUSTHEME { get; set; }
        public string ART_S_SURTHEME { get; set; }
        public Nullable<int> ART_I_RATED { get; set; }
        public Nullable<int> ART_I_NBR_ENRICHISSEMENT { get; set; }
        public string ART_S_CAN_I_ID { get; set; }
        public string ART_S_CANAUX { get; set; }
        public Nullable<bool> ART_B_A_LA_UNE { get; set; }
    
        public virtual ICollection<TP_PAYS> TP_PAYS { get; set; }
    }
}
