//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP_PAYS
    {
        public TP_PAYS()
        {
            this.T_ARTICLES = new HashSet<T_ARTICLES>();
        }
    
        public decimal PAY_I_ID { get; set; }
        public string PAY_S_FR_LIBELLE { get; set; }
        public string PAY_S_AN_LIBELLE { get; set; }
        public string PAY_S_INDICATIF_TEL { get; set; }
        public string PAY_S_INDICATIF_FAX { get; set; }
        public string TVA_S_ID { get; set; }
        public Nullable<int> PAY_B_IsCountry { get; set; }
        public bool PAY_B_IsOld { get; set; }
        public Nullable<int> PAY_I_TARIF_POSTAL { get; set; }
        public string PAY_S_CODE { get; set; }
        public string ZON_S_ID { get; set; }
        public string PAY_S_HTAG_FR { get; set; }
        public string PAY_S_HTAG_AN { get; set; }
    
        public virtual ICollection<T_ARTICLES> T_ARTICLES { get; set; }
    }
}
